### ISSUE TITLE
Streaming anything from Nyaa results in an error

### ISSUE THREAD

**Issue by FlafyDev** [justfoolingaround/animdl#125]
"I have upgraded the project to its latest version, checked the open issues for any duplicates, am not spamming multiple same or similar issues and **have not edited the code myself**. In any of those cases, a maintainer may **CLOSE** or **DELETE** the issue without any notices."

From maintainer: Your title should answer at least 2 or 3 of 5W1H questions for fastest responses.

I have downloaded animdl using `pip install animdl`.

**Describe the bug**
Trying to stream anything from Nyaa results in an error.
The command: `animdl stream "nyaa:your name" -r 1 --auto`
The error: `Exception: Can't find a provider for the url {!r}.`
<details>
<summary>Full output</summary>

```
C:\WINDOWS\system32>animdl stream "nyaa:your name" -r 1 --auto
                                           justfoolingaround/animdl - v1.4.85

                                    A highly efficient anime downloader and streamer

[stream.py:138 - 2022-03-11 20:47:16,388 - nyaa/streamer: I] Now initiating your stream session
Traceback (most recent call last):
  File "D:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python310\Scripts\animdl.exe\__main__.py", line 7, in <module>
  File "D:\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "D:\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python\Python310\lib\site-packages\animdl\core\cli\helpers\fun.py", line 135, in internal
    return f(*args, **kwargs)
  File "D:\Python\Python310\lib\site-packages\animdl\core\cli\commands\stream.py", line 140, in animdl_stream
    enqueuer = providers.get_appropriate(
  File "D:\Python\Python310\lib\site-packages\animdl\core\codebase\providers\__init__.py", line 36, in get_appropriate
    regex_match, provider_module, _ = get_provider(append_protocol(url))
  File "D:\Python\Python310\lib\site-packages\animdl\core\codebase\providers\__init__.py", line 30, in get_provider
    raise Exception("Can't find a provider for the url {!r}.")
Exception: Can't find a provider for the url {!r}.
 
```

</details>

**Did the error occur in between an active task (`download` / `stream` / `grab`)?**
This error occurs in each of the tasks after selecting the index to download.

**Additional information**
- version: `justfoolingaround/animdl - v1.4.85`
- site: Nyaa

**Comment by justfoolingaround** [comment]
Nyaa was removed due to poor torrent support.

When it was present, it relied on qBitTorrent configurations and such so it was deemed a bit difficult for the users. Use `peerflix` or `webtorrent`.
