### ISSUE TITLE
Error when querying stream from "animepahe"

### ISSUE THREAD

**Issue by Armadillidiid** [justfoolingaround/animdl#140]
`Traceback (most recent call last):
  File "/home/emmanuel/.local/bin/animdl", line 8, in <module>
    sys.exit(__animdl_cli__())
  File "/home/emmanuel/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/emmanuel/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/emmanuel/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/emmanuel/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/emmanuel/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/emmanuel/.local/lib/python3.8/site-packages/animdl/core/cli/helpers/fun.py", line 135, in internal
    return f(*args, **kwargs)
  File "/home/emmanuel/.local/lib/python3.8/site-packages/animdl/core/cli/commands/stream.py", line 160, in animdl_stream
    streams = list(
  File "/home/emmanuel/.local/lib/python3.8/site-packages/animdl/core/codebase/providers/animepahe/__init__.py", line 103, in fetcher
    release_id = ID_RE.search(anime_page.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

xxxxx@xxxxx-HP-Omen:~$ animdl stream "https://animepahe.com/play/b0957d72-4aac-44d6-d0a6-5c275d9e8c1e/c99caabc4bc947589f3f82c9564d78682a416a7d14c3f3985247d6bc6b2411f4/" -r 1`

**Comment by justfoolingaround** [comment]
Fixed as of `1.5.75`.
