### ISSUE TITLE
I can't download a certain anime from animixplay

### ISSUE THREAD

**Issue by Jurrein** [justfoolingaround/animdl#144]
Hi, 
when I tried to use this command:"animdl download "animixplay:Tensei shitara Slime Datta Ken" -r 1-? -q 1080p/720p" , and then selected 01, or the first season, I get an error, while when i do the same command and select season 2, or 02, it works perfectly fine. It sends an error code which I will put below. 
I used the latest version, downloaded via pip(v1.5.76) with python 3.10.4 installed(also latest I think) and I have not edited the code, nor do I know how to do that.
Thanks! Your project works perfectly fine otherwise.

Error code:
C:\Users\jurrien>animdl download "animixplay:Tensei shitara Slime Datta Ken" -r 1-? -q 1080p/720p
                                           justfoolingaround/animdl - v1.5.76                                           
                                    A highly efficient anime downloader and streamer                                    
[prompts.py:37 - 2022-05-24 13:43:22,265 - downloader: I] 01: Tensei shitara Slime Datta Ken / https://animixplay.to/v1/tensei-shitara-slime-datta-ken
[prompts.py:37 - 2022-05-24 13:43:22,267 - downloader: I] 02: Tensei shitara Slime Datta Ken 2nd Season / https://animixplay.to/v1/tensei-shitara-slime-datta-ken-2nd-season
[prompts.py:37 - 2022-05-24 13:43:22,267 - downloader: I] 03: Tensei shitara Slime Datta Ken 2nd Season (Dub) / https://animixplay.to/v1/tensei-shitara-slime-datta-ken-2nd-season-dub
[prompts.py:37 - 2022-05-24 13:43:22,268 - downloader: I] 04: Tensei shitara Slime Datta Ken 2nd Season Part 2 / https://animixplay.to/v1/tensei-shitara-slime-datta-ken-2nd-season-part-2
[prompts.py:37 - 2022-05-24 13:43:22,268 - downloader: I] 05: Tensei shitara Slime Datta Ken 2nd Season Part 2 (Dub) / https://animixplay.to/v1/tensei-shitara-slime-datta-ken-2nd-season-part-2-dub
[prompts.py:37 - 2022-05-24 13:43:22,269 - downloader: I] 06: Tensei shitara Slime Datta Ken (Dub) / https://animixplay.to/v1/tensei-shitara-slime-datta-ken-dub
Select the search result using index [1]: 01
Traceback (most recent call last):
  File "C:\Users\jurrien\AppData\Local\Programs\Python\Python310\Scripts\animdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('animdl==1.5.76', 'console_scripts', 'animdl')())
  File "C:\Users\jurrien\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\jurrien\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\jurrien\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\jurrien\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\jurrien\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\jurrien\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\helpers\fun.py", line 135, in internal
    return f(*args, **kwargs)
  File "C:\Users\jurrien\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\commands\download.py", line 93, in animdl_download
    streams = list(
  File "C:\Users\jurrien\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\codebase\providers\animixplay\stream_url.py", line 107, in fetcher
    for value in range(data.get("eptotal")):
TypeError: 'str' object cannot be interpreted as an integer

**Comment by Jurrein** [comment]
On a completely different note, is it possible to specify file type? Like -q but with fily type, so TS or MP4? This is because TS files are, in my experience, much larger than mp4 files, so it would drastically improve download speed. Let me know!

**Comment by justfoolingaround** [comment]
Fixed as of `1.5.84`.

**Comment by justfoolingaround** [comment]
> On a completely different note, is it possible to specify file type? Like -q but with file type, so TS or MP4? This is because TS files are, in my experience, much larger than mp4 files, so it would drastically improve download speed. Let me know!

If you're using `animixplay` and getting TS files, you might as well be getting the highest quality streams from Crunchyroll. Moreover, the project just gets what the providers gives, so it isn't technically possible to do so.
