### ISSUE TITLE
Cannot Upgrade to the latest version

### ISSUE THREAD

**Issue by NaiveInvestigator** [justfoolingaround/animdl#152]
Terminal Output:
```
Requirement already satisfied: animdl in c:\users\akid\appdata\local\programs\python\python310\lib\site-packages (1.5.81)
Collecting animdl
  Using cached animdl-1.5.84.tar.gz (76 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Akid\AppData\Local\Temp\pip-install-_p95c55h\animdl_f140151d27774df293efdb2458b9eea3\setup.py", line 4, in <module>
          with open("requirements.txt") as requirements_txt:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I don't not know why this is happening. I also tried running as administrator so there should be no problems regarding permissions hopefully.

**Comment by justfoolingaround** [comment]
Finally fixed as if `1.5.87`. Thanks for the report.
