### ISSUE TITLE
-s latest with or without --auto --index don't work anymore as of  v.1.6.11

### ISSUE THREAD

**Issue by ttx99** [justfoolingaround/animdl#158]
### **_animdl stream "boruto" -s latest_**
                  justfoolingaround/animdl - v1.6.11                  
         A highly efficient, powerful and fast anime scraper.         
[prompts.py:40 - 2022-06-23 05:34:08,650 - streamer: INFO] 01: Boruto: Naruto the Movie / https://gogoanime.pe/category/boruto-naruto-the-movie
[prompts.py:40 - 2022-06-23 05:34:08,651 - streamer: INFO] 02: Boruto: Naruto the Movie (Dub) / https://gogoanime.pe/category/boruto-naruto-the-movie-dub
[prompts.py:40 - 2022-06-23 05:34:08,651 - streamer: INFO] 03: Boruto: Naruto Next Generations / https://gogoanime.pe/category/boruto-naruto-next-generations
[prompts.py:40 - 2022-06-23 05:34:08,651 - streamer: INFO] 04: Boruto: Naruto Next Generations (Dub) / https://gogoanime.pe/category/boruto-naruto-next-generations-dub
[prompts.py:40 - 2022-06-23 05:34:08,651 - streamer: INFO] 05: Boruto: Naruto the Movie - Naruto ga Hokage ni Natta Hi / https://gogoanime.pe/category/boruto-naruto-the-movie-naruto-ga-hokage-ni-natta-hi
[prompts.py:40 - 2022-06-23 05:34:08,651 - streamer: INFO] 06: Boruto: Naruto the Movie - Naruto ga Hokage ni Natta Hi (Dub) / https://gogoanime.pe/category/boruto-naruto-the-movie-naruto-ga-hokage-ni-natta-hi-dub
### **_Select the search result using index [1]: 3_**
[stream.py:68 - 2022-06-23 05:34:51,155 - gogoanime/streamer: INFO] Now initiating your stream session
Traceback (most recent call last):
  File "/home/mac7/.local/bin/animdl", line 8, in <module>
    sys.exit(__animdl_cli__())
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mac7/.local/lib/python3.8/site-packages/animdl/core/cli/helpers/logger.py", line 79, in __inner__
    return f(*args, **kwargs, log_file=log_file, log_level=log_level)
  File "/home/mac7/.local/lib/python3.8/site-packages/animdl/core/cli/helpers/banner.py", line 65, in __inner__
    return f(*args, log_level=log_level, log_file=log_file, **kwargs)
  File "/home/mac7/.local/lib/python3.8/site-packages/animdl/core/cli/commands/stream.py", line 79, in animdl_stream
    streams = list(helpers.special_parser(streams, special))
AttributeError: module 'animdl.core.cli.helpers' has no attribute 'special_parser'

### **_animdl stream "boruto" -s latest --auto --index 3_**
Usage: animdl stream [OPTIONS] QUERY
Try 'animdl stream --help' for help.

**Comment by justfoolingaround** [comment]
`--auto` has been removed. Simply giving a value to `--index` will work now.

**Comment by ttx99** [comment]
Ok please update readme.  But how about the   **-s latest with or without --index?**

**with **-s latest**** 

**animdl stream "boruto" -s latest** 
                                                                                                 justfoolingaround/animdl - v1.6.11                                                                                                  
                                                                                        A highly efficient, powerful and fast anime scraper.                                                                                         
[prompts.py:40 - 2022-06-23 14:26:52,340 - streamer: INFO] 01: Boruto: Naruto the Movie / https://gogoanime.pe/category/boruto-naruto-the-movie
[prompts.py:40 - 2022-06-23 14:26:52,340 - streamer: INFO] 02: Boruto: Naruto the Movie (Dub) / https://gogoanime.pe/category/boruto-naruto-the-movie-dub
[prompts.py:40 - 2022-06-23 14:26:52,340 - streamer: INFO] 03: Boruto: Naruto Next Generations / https://gogoanime.pe/category/boruto-naruto-next-generations
[prompts.py:40 - 2022-06-23 14:26:52,340 - streamer: INFO] 04: Boruto: Naruto Next Generations (Dub) / https://gogoanime.pe/category/boruto-naruto-next-generations-dub
[prompts.py:40 - 2022-06-23 14:26:52,340 - streamer: INFO] 05: Boruto: Naruto the Movie - Naruto ga Hokage ni Natta Hi / https://gogoanime.pe/category/boruto-naruto-the-movie-naruto-ga-hokage-ni-natta-hi
[prompts.py:40 - 2022-06-23 14:26:52,341 - streamer: INFO] 06: Boruto: Naruto the Movie - Naruto ga Hokage ni Natta Hi (Dub) / https://gogoanime.pe/category/boruto-naruto-the-movie-naruto-ga-hokage-ni-natta-hi-dub
**Select the search result using index [1]: 3**
[stream.py:68 - 2022-06-23 14:27:01,804 - gogoanime/streamer: INFO] Now initiating your stream session
Traceback (most recent call last):
  File "/home/mac7/.local/bin/animdl", line 8, in <module>
    sys.exit(__animdl_cli__())
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mac7/.local/lib/python3.8/site-packages/animdl/core/cli/helpers/logger.py", line 79, in __inner__
    return f(*args, **kwargs, log_file=log_file, log_level=log_level)
  File "/home/mac7/.local/lib/python3.8/site-packages/animdl/core/cli/helpers/banner.py", line 65, in __inner__
    return f(*args, log_level=log_level, log_file=log_file, **kwargs)
  File "/home/mac7/.local/lib/python3.8/site-packages/animdl/core/cli/commands/stream.py", line 79, in animdl_stream
    streams = list(helpers.special_parser(streams, special))
AttributeError: module 'animdl.core.cli.helpers' has no attribute 'special_parser'


**with -s latest and --index**

**animdl stream "boruto" -s latest --index 3**
                                                                                                 justfoolingaround/animdl - v1.6.11                                                                                                  
                                                                                        A highly efficient, powerful and fast anime scraper.                                                                                         
[stream.py:68 - 2022-06-23 14:28:28,058 - gogoanime/streamer: INFO] Now initiating your stream session
Traceback (most recent call last):
  File "/home/mac7/.local/bin/animdl", line 8, in <module>
    sys.exit(__animdl_cli__())
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mac7/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mac7/.local/lib/python3.8/site-packages/animdl/core/cli/helpers/logger.py", line 79, in __inner__
    return f(*args, **kwargs, log_file=log_file, log_level=log_level)
  File "/home/mac7/.local/lib/python3.8/site-packages/animdl/core/cli/helpers/banner.py", line 65, in __inner__
    return f(*args, log_level=log_level, log_file=log_file, **kwargs)
  File "/home/mac7/.local/lib/python3.8/site-packages/animdl/core/cli/commands/stream.py", line 79, in animdl_stream
    streams = list(helpers.special_parser(streams, special))
AttributeError: module 'animdl.core.cli.helpers' has no attribute 'special_parser'

**Comment by justfoolingaround** [comment]
Oof will fix. Removed import during refactor :/.

**Comment by brahmkshatriya** [comment]
Which is simply why one should not auto refactoring :okAnd:

**Comment by justfoolingaround** [comment]
Fixed as of 1.6.12.
