### ISSUE TITLE
animixplay returns error "Failed to find anything of that query on 'animixplay'. Try searching on other providers."

### ISSUE THREAD

**Issue by rutgerrrrr** [justfoolingaround/animdl#160]
This happens for me on multiple versions up to v1.6.16, MacOS. For some reason animixplay seems to be unreachable through animdl, did they change anything on their end? Other providers seem to work just fine. I've noticed this since yesterday, July 3rd 2022.

Below is my put for `$animdl grab "bleach`

```
     justfoolingaround/animdl - v1.6.16                                                                              
     A highly efficient, powerful and fast anime scraper.     
                                                                
[prompts.py:31 - 2022-07-04 09:44:43,420 - grabber: CRITICAL] Failed to find anything of that query on 'animixplay'. Try searching on other providers.
[grab.py:39 - 2022-07-04 09:44:43,420 - None/grabber: INFO] Initializing grabbing session.
Traceback (most recent call last):
  File "/usr/local/bin/animdl", line 8, in <module>
    sys.exit(__animdl_cli__())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/animdl/core/cli/helpers/logger.py", line 79, in __inner__
    return f(*args, **kwargs, log_file=log_file, log_level=log_level)
  File "/usr/local/lib/python3.9/site-packages/animdl/core/cli/helpers/banner.py", line 65, in __inner__
    return f(*args, log_level=log_level, log_file=log_file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/animdl/core/cli/commands/grab.py", line 41, in animdl_grab
    for stream_url_caller, episode in providers.get_appropriate(
  File "/usr/local/lib/python3.9/site-packages/animdl/core/codebase/providers/__init__.py", line 35, in get_appropriate
    regex_match, provider_module, _ = get_provider(append_protocol(url))
  File "/usr/local/lib/python3.9/site-packages/animdl/core/codebase/helper/__init__.py", line 25, in append_protocol
    if regex.search(r"^.+?://", uri):
  File "/usr/local/lib/python3.9/site-packages/regex/regex.py", line 268, in search
    return pat.search(string, pos, endpos, concurrent, partial, timeout)
TypeError: expected string or buffer

```

**Comment by uzuto** [comment]
Just update the app, It's working fine.

**Comment by justfoolingaround** [comment]
This should be working as of the recent updates. Sorry for the inconvenience.
