### ISSUE TITLE
Animepahe not showing entries

### ISSUE THREAD

**Issue by NaiveInvestigator** [justfoolingaround/animdl#167]
Terminal Output:
```
animdl stream "animepahe:"
                                      justfoolingaround/animdl - v1.6.20
                             A highly efficient, powerful and fast anime scraper.
Traceback (most recent call last):
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\Scripts\animdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\helpers\logger.py", line 79, in __inner__
    return f(*args, **kwargs, log_file=log_file, log_level=log_level)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\helpers\banner.py", line 101, in __inner__
    return f(*args, log_level=log_level, log_file=log_file, **kwargs)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\commands\stream.py", line 58, in animdl_stream
    anime, provider = helpers.process_query(
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\helpers\processors.py", line 41, in process_query
    return prompt_user(logger, genexp, provider)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\helpers\processors.py", line 10, in prompt_user
    return manager(
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\helpers\prompts.py", line 75, in fzf_prompt
    components = list(processor(component) for component in components)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\helpers\prompts.py", line 75, in <genexpr>
    components = list(processor(component) for component in components)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\helpers\searcher.py", line 85, in search_animepahe
    content = animepahe_results.json()
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Edit: After this i tried `animepahe stream "animepahe:Bleach"`, that worked tho, so np there. Really minor issue, but thought you'd like to know.

**Comment by justfoolingaround** [comment]
Seems to be working at the moment, probably Cloudflare triggered when you used that. Also send in a query when using provider specific search.

![image](https://user-images.githubusercontent.com/79979949/181878592-f38a80af-23b4-4ee7-8f84-2ae8fceb70bc.png)
