### ISSUE TITLE
Zoro scraper broken

### ISSUE THREAD

**Issue by beam2546** [justfoolingaround/animdl#180]
**Describe the bug**
Zoro scraper might be broken. Zoro work fine on my browser and Animixplay scraper work fine without any issue.

**Did the error occur in between an active task (`download` / `stream` / `grab`)?**
Both download, stream and grab are broken

**Screenshots [Optional]**
![image](https://user-images.githubusercontent.com/10400894/190894378-8571c7ac-7d4d-4b8b-a7e2-682b5b697192.png)

**Additional information**
- animdl version: Latest version from git pull

Full error:
```
Exception in thread Thread-1 (ws_stimulation):
Traceback (most recent call last):
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpcore\backends\sync.py", line 86, in connect_tcp
    sock = socket.create_connection(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
    raise exc
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpcore\_sync\connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpcore\backends\sync.py", line 85, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Beam2546\animdl\animdl\core\codebase\extractors\rapidvideo\polling.py", line 42, in ws_stimulation
    _, response = ws_poll()
  File "C:\Users\Beam2546\animdl\animdl\core\codebase\extractors\rapidvideo\polling.py", line 36, in ws_poll
    response = session.get(url, params=soft)
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_client.py", line 1039, in get
    return self.request(
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_client.py", line 815, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_client.py", line 902, in send
    response = self._send_handling_auth(
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_client.py", line 930, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_client.py", line 967, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_client.py", line 1003, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_transports\default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Beam2546\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

```

**Comment by justfoolingaround** [comment]
Fixed as of `1.6.22`.
