### ISSUE TITLE
Broken on python 3.11

### ISSUE THREAD

**Issue by BloodZero0** [justfoolingaround/animdl#193]
On python 3.11 the program is broken, I always get this error: 
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\onepi\scoop\apps\python\current\Scripts\animdl.exe\__main__.py", line 4, in <module>
  File "C:\Users\onepi\scoop\apps\python\current\Lib\site-packages\animdl\__main__.py", line 8, in <module>
    from .core.cli.commands import download, grab, schedule, search, stream, update
  File "C:\Users\onepi\scoop\apps\python\current\Lib\site-packages\animdl\core\cli\commands\download.py", line 7, in <module>
    from ...codebase import providers, sanitize_filename
  File "C:\Users\onepi\scoop\apps\python\current\Lib\site-packages\animdl\core\codebase\__init__.py", line 1, in <module>
    from .downloader import *
  File "C:\Users\onepi\scoop\apps\python\current\Lib\site-packages\animdl\core\codebase\downloader\__init__.py", line 1, in <module>
    from .handle import handle_download, sanitize_filename
  File "C:\Users\onepi\scoop\apps\python\current\Lib\site-packages\animdl\core\codebase\downloader\handle.py", line 7, in <module>
    import regex
  File "C:\Users\onepi\scoop\apps\python\current\Lib\site-packages\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Users\onepi\scoop\apps\python\current\Lib\site-packages\regex\regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "C:\Users\onepi\scoop\apps\python\current\Lib\site-packages\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'`

**Comment by rares9301** [comment]
tried installing it right now, getting thrown to some bs multidict and yarl error. Will install the Visual Studio Build Tools for C++ and i will come back with an update.

**Comment by rares9301** [comment]
im back with the update, installing MS VSBT 14.0 C++ fixed the multidict error but did shit for the yarl one
_quoting_c.c
      yarl/_quoting_c.c(198): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or director
no interpretor in 3.11, seems like i will roll back to 3.10

**Comment by rares9301** [comment]
rolled back to 3.10, got the issue fixed. the interface looks old but its working :D

**Comment by justfoolingaround** [comment]
I might as well include that Python 3.11 is not supported and is not planned until the dependencies will be fully supporting it.

**Comment by FollieHiyuki** [comment]
`yarl==1.8.1` can be installed without error with `pip`, so a version bump for it probably will fix the issue.

**Comment by justfoolingaround** [comment]
Aight, `yarl` has been set to 1.8.1. Python 3.11 should now be supported. Thank you!
