### ISSUE TITLE
Dependency issue? "No module named 'regex._regex'"

### ISSUE THREAD

**Issue by IngwiePhoenix** [justfoolingaround/animdl#199]
**Describe the bug**

I tried installing `animdl` on my OpenWrt router. Now, I am well aware that OpenWrt is not exactly ment to do the things I am making it do - but I have it running on an absolutely beefy SBC (FriendlyElec NanoPi R6s, big.LITTLE with 4+4 cores and 8GB RAM) and use it as a home-server. My goal is to offload downloading to it :)

I used the PIP install method (versions below) and was met with the error from the title.

**Did the error occur in between an active task (`download` / `stream` / `grab`)?**
No.

**Screenshots [Optional]**
None, but here is the output of installing and trying to use:
```
root@FriendlyWrt ~/.c/fish [1]# pip install animdl
Collecting animdl
  Downloading animdl-1.6.33.tar.gz (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 17.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting anchor-kr==0.1.3
  Downloading anchor-kr-0.1.3.tar.gz (5.2 kB)
  Preparing metadata (setup.py) ... done
Collecting anitopy==2.1.0
  Downloading anitopy-2.1.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting click==8.0.4
  Downloading click-8.0.4-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.5/97.5 kB 16.5 MB/s eta 0:00:00
Collecting comtypes==1.1.11
  Downloading comtypes-1.1.11-py2.py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.4/167.4 kB 25.1 MB/s eta 0:00:00
Collecting cssselect==1.1.0
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting httpx==0.23.0
  Downloading httpx-0.23.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 22.3 MB/s eta 0:00:00
Collecting lxml==4.9.1
  Downloading lxml-4.9.1-cp310-cp310-musllinux_1_1_aarch64.whl (7.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 11.8 MB/s eta 0:00:00
Collecting tqdm==4.62.3
  Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.2/76.2 kB 20.7 MB/s eta 0:00:00
Collecting pycryptodomex==3.14.1
  Downloading pycryptodomex-3.14.1.tar.gz (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 11.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting regex==2022.3.15
  Downloading regex-2022.3.15-cp310-cp310-musllinux_1_1_aarch64.whl (732 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 732.0/732.0 kB 11.1 MB/s eta 0:00:00
Collecting yarl==1.8.1
  Downloading yarl-1.8.1-cp310-cp310-musllinux_1_1_aarch64.whl (241 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.6/241.6 kB 11.9 MB/s eta 0:00:00
Collecting pyyaml==6.0
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 25.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting httpcore<0.16.0,>=0.15.0
  Downloading httpcore-0.15.0-py3-none-any.whl (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.4/68.4 kB 5.4 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/lib/python3.10/site-packages (from httpx==0.23.0->animdl) (2022.12.7)
Collecting rfc3986[idna2008]<2,>=1.3
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting sniffio
  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting idna>=2.0
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 4.7 MB/s eta 0:00:00
Collecting multidict>=4.0
  Downloading multidict-6.0.3-cp310-cp310-musllinux_1_1_aarch64.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.6/138.6 kB 8.4 MB/s eta 0:00:00
Collecting h11<0.13,>=0.11
  Downloading h11-0.12.0-py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.9/54.9 kB 10.7 MB/s eta 0:00:00
Collecting anyio==3.*
  Downloading anyio-3.6.2-py3-none-any.whl (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 kB 19.3 MB/s eta 0:00:00
Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (pyproject.toml) ... done
  Created wheel for pyyaml: filename=PyYAML-6.0-cp310-cp310-linux_aarch64.whl size=45335 sha256=7414c2f6b080c1cc0bae84e8ab2b8f44710784102deac69c8f6d699c8d1f65af
  Stored in directory: /tmp/.cache/wheels/06/72/f6/3f89f64cf1943a82e42cdd8e59d7b2aa98769fd48b08019fc7
Successfully built pyyaml
Installing collected packages: rfc3986, comtypes, anchor-kr, tqdm, sniffio, regex, pyyaml, pycryptodomex, multidict, lxml, idna, h11, cssselect, click, anitopy, yarl, anyio, httpcore, httpx, animdl
  DEPRECATION: anchor-kr is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for anchor-kr ... done
  Attempting uninstall: pycryptodomex
    Found existing installation: pycryptodomex 3.16.0
    Uninstalling pycryptodomex-3.16.0:
      Successfully uninstalled pycryptodomex-3.16.0
  DEPRECATION: pycryptodomex is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pycryptodomex ... done
  DEPRECATION: anitopy is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for anitopy ... done
  DEPRECATION: animdl is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for animdl ... done
Successfully installed anchor-kr-0.1.3 animdl-1.6.33 anitopy-2.1.0 anyio-3.6.2 click-8.0.4 comtypes-1.1.11 cssselect-1.1.0 h11-0.12.0 httpcore-0.15.0 httpx-0.23.0 idna-3.4 lxml-4.9.1 multidict-6.0.3 pycryptodomex-3.14.1 pyyaml-6.0 regex-2022.3.15 rfc3986-1.5.0 sniffio-1.3.0 tqdm-4.62.3 yarl-1.8.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@FriendlyWrt ~/.c/fish# pip install wheel
Collecting wheel
  Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
Installing collected packages: wheel
Successfully installed wheel-0.38.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@FriendlyWrt ~/.c/fish# animdl --help
Traceback (most recent call last):
  File "/usr/bin/animdl", line 33, in <module>
    sys.exit(load_entry_point('animdl==1.6.33', 'console_scripts', 'animdl')())
  File "/usr/bin/animdl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/animdl/__main__.py", line 8, in <module>
    from .core.cli.commands import download, grab, schedule, search, stream, update
  File "/usr/lib/python3.10/site-packages/animdl/core/cli/commands/download.py", line 7, in <module>
    from ...codebase import providers, sanitize_filename
  File "/usr/lib/python3.10/site-packages/animdl/core/codebase/__init__.py", line 1, in <module>
    from .downloader import *
  File "/usr/lib/python3.10/site-packages/animdl/core/codebase/downloader/__init__.py", line 1, in <module>
    from .handle import handle_download, sanitize_filename
  File "/usr/lib/python3.10/site-packages/animdl/core/codebase/downloader/handle.py", line 7, in <module>
    import regex
  File "/usr/lib/python3.10/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/usr/lib/python3.10/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/usr/lib/python3.10/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'
root@FriendlyWrt ~/.c/fish [1]# pip install regex
Requirement already satisfied: regex in /usr/lib/python3.10/site-packages (2022.3.15)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@FriendlyWrt ~/.c/fish# animdl --help
Traceback (most recent call last):
  File "/usr/bin/animdl", line 33, in <module>
    sys.exit(load_entry_point('animdl==1.6.33', 'console_scripts', 'animdl')())
  File "/usr/bin/animdl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/animdl/__main__.py", line 8, in <module>
    from .core.cli.commands import download, grab, schedule, search, stream, update
  File "/usr/lib/python3.10/site-packages/animdl/core/cli/commands/download.py", line 7, in <module>
    from ...codebase import providers, sanitize_filename
  File "/usr/lib/python3.10/site-packages/animdl/core/codebase/__init__.py", line 1, in <module>
    from .downloader import *
  File "/usr/lib/python3.10/site-packages/animdl/core/codebase/downloader/__init__.py", line 1, in <module>
    from .handle import handle_download, sanitize_filename
  File "/usr/lib/python3.10/site-packages/animdl/core/codebase/downloader/handle.py", line 7, in <module>
    import regex
  File "/usr/lib/python3.10/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/usr/lib/python3.10/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/usr/lib/python3.10/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'
```

Here is my version information:
```
root@FriendlyWrt ~/.c/fish# python --version
Python 3.10.7
root@FriendlyWrt ~/.c/fish# pip --version
pip 22.3.1 from /root/.local/lib/python3.10/site-packages/pip (python 3.10)
```

I do have all the packages that make a regular `build-essentials` (make, gcc, autoconf, ...) installed, so native extensions should definitively build.

**Additional information**
- animdl version: Latest from pip - but, I can't exactly check via the cli, sorry :). Going by the logs, however, it seems to be `1.6.33`.
- The site and provider this issue is related to: None

**Comment by IngwiePhoenix** [comment]
Small appendix, I looked at the installed RegEx module:

```
/usr/lib/python3.10/site-packages/regex/
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-310.pyc
│   ├── _regex_core.cpython-310.pyc
│   ├── regex.cpython-310.pyc
│   └── test_regex.cpython-310.pyc
├── _regex.cpython-310-aarch64-linux-gnu.so
├── _regex_core.py
├── regex.py
└── test_regex.py
```

I took the path from the trace. And, I am also not very good with Python... ^^'

**Comment by IngwiePhoenix** [comment]
This turned out to be a non-issue.

Long story short: The Python compiled for OpenWrt has a build problem - causing a few native compiled libs to be broken. RegEx is one of them. I worked around this, eventually... Sorry for the bother!
