### ISSUE TITLE
[Feature Request] Auto retry after error

### ISSUE THREAD

**Issue by shadow5013** [justfoolingaround/animdl#20]
Sorry for bothering you again and again. I have got this error several times while downloading. If I rerun the command it goes away. It might be caused by my unstable internet connection. Adding auto retry might help.
```bash
 ./animdl.py download "animepahe:B the beginning succession"
░█████╗░███╗░░██╗██╗███╗░░░███╗██████╗░██╗░░░░░
██╔══██╗████╗░██║██║████╗░████║██╔══██╗██║░░░░░
███████║██╔██╗██║██║██╔████╔██║██║░░██║██║░░░░░
██╔══██║██║╚████║██║██║╚██╔╝██║██║░░██║██║░░░░░
██║░░██║██║░╚███║██║██║░╚═╝░██║██████╔╝███████╗
╚═╝░░╚═╝╚═╝░░╚══╝╚═╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝v1.3.0
A highly efficient anime downloader and streamer

[animdl-animepahe-searcher] [#01] B: The Beginning Succession https://animepahe.com/anime/cdbcd889-ba5a-e1f2-cc8a-d790d0e2a4fa
Select by the index (defaults to 1): 
[animdl-animepahe-downloader-core] Initializing download session [00 -> ?]
[animdl-animepahe-downloader-core] Starting download session [00 -> 5]
[animdl-animepahe-downloader-core] Downloads will be done in the folder 'B: The Beginning Succession'
[HLS] E01 : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 147/147 [01:05<00:00,  2.24ts/s]
[HLS] E02 : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 142/142 [01:00<00:00,  2.36ts/s]
[HLS] E03 :  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 135/145 [00:55<00:04,  2.47ts/s]
Traceback (most recent call last):
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shadow/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shadow/animdl/./animdl.py", line 31, in <module>
    __animdl_cli__()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/shadow/animdl/core/cli/commands/download.py", line 87, in animdl_download
    hls_download(stream_urls, base / ("%s.ts" % sanitize_filename(content_title)), content_title)
  File "/home/shadow/animdl/core/codebase/downloader/download.py", line 54, in hls_download
    for content in hls_yield(session, quality_dict):
  File "/home/shadow/animdl/core/codebase/downloader/hls_download.py", line 87, in hls_yield
    with session.get(ts_uris, headers=headers, verify=ssl_verification) as ts_response:
  File "/home/shadow/.local/lib/python3.9/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/shadow/.local/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/shadow/.local/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/shadow/.local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[HLS] E03 :  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 135/145 [00:56<00:04,  2.41ts/s]
```

**Comment by justfoolingaround** [comment]
My bad, I forgot an auto-retry for HLS. It should be there now!

**Comment by shadow5013** [comment]
@justfoolingaround Sorry for late reply. I did some testing. It is indeed solved for HLS stream. But I can still reproduce the issue for normal downloading.
```bash
$ ./animdl.py download "anime1:kiznaiver"
░█████╗░███╗░░██╗██╗███╗░░░███╗██████╗░██╗░░░░░
██╔══██╗████╗░██║██║████╗░████║██╔══██╗██║░░░░░
███████║██╔██╗██║██║██╔████╔██║██║░░██║██║░░░░░
██╔══██║██║╚████║██║██║╚██╔╝██║██║░░██║██║░░░░░
██║░░██║██║░╚███║██║██║░╚═╝░██║██████╔╝███████╗
╚═╝░░╚═╝╚═╝░░╚══╝╚═╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝v1.3.0
A highly efficient anime downloader and streamer

[animdl-anime1-searcher] [#01] Kiznaiver https://www.anime1.com/watch/kiznaiver
Select by the index (defaults to 1): [animdl-anime1-downloader-core] Initializing download session [00 -> ?]
[animdl-anime1-downloader-core] Starting download session [00 -> 11]
[animdl-anime1-downloader-core] Downloads will be done in the folder 'Kiznaiver'
E01: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 115M/115M [01:02<00:00, 1.95MB/s]
Traceback (most recent call last):
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shadow/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/shadow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shadow/animdl/./animdl.py", line 31, in <module>
    __animdl_cli__()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/shadow/animdl/core/cli/commands/download.py", line 67, in animdl_download
    stream_urls = stream_url_caller()
  File "/home/shadow/animdl/core/codebase/providers/anime1/__init__.py", line 20, in extract
    with session.get(url, verify=False) as episode:
  File "/home/shadow/.local/lib/python3.9/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/shadow/.local/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/shadow/.local/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/shadow/.local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by justfoolingaround** [comment]
That error seems to be occurring when accessing Anime1's site during extraction and not with downloading. 
![image](https://user-images.githubusercontent.com/79979949/124459062-795ab300-ddad-11eb-826b-ed4042c0231d.png)
You can see it's not reproducible during a `grab` (it goes the same process for extraction as `download`).

All I can say without any mechanisms to reproduce is.. just retry it. The only possible fix that I can think of is subclassing `requests.Session` to overload the default request sender with an auto retry which would endlessly request content (this is a possible fix however there's no way this is going to be implemented.)
