### ISSUE TITLE
Allanime is broken

### ISSUE THREAD

**Issue by toomyzoom** [justfoolingaround/animdl#202]
**Describe the bug**

A clear and concise description of what the bug is. This includes whether the bug wasn't there in previous versions (in which case you're expected to provide a version number.)

`animdl grab 'allanime:black lagoon'`

````

> Traceback (most recent call last):
>   File "/usr/bin/animdl", line 33, in <module>
>     sys.exit(load_entry_point('animdl==1.6.36', 'console_scripts', 'animdl')())
>   File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/animdl/core/cli/helpers/logger.py", line 79, in __inner__
>     return f(*args, **kwargs, log_file=log_file, log_level=log_level)
>   File "/usr/lib/python3.10/site-packages/animdl/core/cli/helpers/banner.py", line 97, in __inner__
>     return f(*args, log_level=log_level, log_file=log_file, **kwargs)
>   File "/usr/lib/python3.10/site-packages/animdl/core/cli/commands/grab.py", line 31, in animdl_grab
>     anime, provider = helpers.process_query(
>   File "/usr/lib/python3.10/site-packages/animdl/core/cli/helpers/processors.py", line 41, in process_query
>     return prompt_user(logger, genexp, provider)
>   File "/usr/lib/python3.10/site-packages/animdl/core/cli/helpers/processors.py", line 10, in prompt_user
>     return manager(
>   File "/usr/lib/python3.10/site-packages/animdl/core/cli/helpers/prompts.py", line 27, in default_prompt
>     components = list(processor(component) for component in components)
>   File "/usr/lib/python3.10/site-packages/animdl/core/cli/helpers/prompts.py", line 27, in <genexpr>
>     components = list(processor(component) for component in components)
>   File "/usr/lib/python3.10/site-packages/animdl/core/cli/helpers/searcher.py", line 71, in search_allanime
>     for result in gql_response.json().get("data", {}).get("shows", {}).get("edges", []):
>   File "/usr/lib/python3.10/site-packages/httpx/_models.py", line 752, in json
>     return jsonlib.loads(self.text, **kwargs)
>   File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

````

**Did the error occur in between an active task (`download` / `stream` / `grab`)?**

This indicates if the scraper or program is broken totally or the scraper or program may have a few issues on the inside.

See log above

**Screenshots [Optional]**

**Additional information**
- animdl version: 1.6.36'
- The site and provider this issue is related to: allanime

**Comment by justfoolingaround** [comment]
Fixed as of `1.6.39`.
