### ISSUE TITLE
Program crashes with last error being "TypeError: string indices must be integers"

### ISSUE THREAD

**Issue by patgamer351** [justfoolingaround/animdl#207]
I have used this program before to download a few episodes before but this time when I tried to download "Sawayaki Kitsune no Senko-San" by running `animdl download "senko-san"` and selecting the only index but it gives a traceback with: 

Traceback (most recent call last):
  File "/home/patrick/.local/bin/./animdl", line 8, in <module>
    sys.exit(__animdl_cli__())
  File "/home/patrick/.local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/patrick/.local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/patrick/.local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/patrick/.local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/patrick/.local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/patrick/.local/lib/python3.10/site-packages/animdl/core/cli/helpers/logger.py", line 79, in __inner__
    return f(*args, **kwargs, log_file=log_file, log_level=log_level)
  File "/home/patrick/.local/lib/python3.10/site-packages/animdl/core/cli/helpers/banner.py", line 97, in __inner__
    return f(*args, log_level=log_level, log_file=log_file, **kwargs)
  File "/home/patrick/.local/lib/python3.10/site-packages/animdl/core/cli/commands/download.py", line 90, in animdl_download
    success, reason = helpers.download(
  File "/home/patrick/.local/lib/python3.10/site-packages/animdl/core/cli/helpers/__init__.py", line 63, in download
    downloadable_content = intelliq.filter_quality(list(stream_urls), quality)
  File "/home/patrick/.local/lib/python3.10/site-packages/animdl/core/cli/helpers/__init__.py", line 52, in ensure_extraction
    for stream in stream_uri_caller():
  File "/home/patrick/.local/lib/python3.10/site-packages/animdl/core/codebase/providers/allanime/__init__.py", line 166, in <lambda>
    lambda session, content: list(
  File "/home/patrick/.local/lib/python3.10/site-packages/animdl/core/codebase/providers/allanime/__init__.py", line 143, in extract_content
    child = next(iterator, None)
  File "/home/patrick/.local/lib/python3.10/site-packages/animdl/core/codebase/providers/allanime/__init__.py", line 98, in iter_prioritised
    yield list(iter_all())
  File "/home/patrick/.local/lib/python3.10/site-packages/animdl/core/codebase/providers/allanime/__init__.py", line 90, in iter_all
    stream_url = link["link"]
TypeError: string indices must be integers

thanks for the amazing program!

**Comment by toomyzoom** [comment]
Version ?

**Comment by patgamer351** [comment]
latest version i did a git pull and also i ran this both on Ubuntu 20.04 and Gentoo and both did the same thing

**Comment by justfoolingaround** [comment]
Fixed as of `1.6.52`. Sorry for the inconvenience. There were some inconsistent results from the site!

**Comment by patgamer351** [comment]
it works now, thanks for the fix!!
