### ISSUE TITLE
continue not working || am I doing it wrong ?

### ISSUE THREAD

**Issue by shahrier-nafis** [justfoolingaround/animdl#26]
**I typed ::: animedl continue ["identifier":  from cli_session_animdl ]**
**I typed ::: animedl continue "dragon ball (dub)"**
Traceback (most recent call last):
  File "C:\Python39\Scripts\animdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('animdl==1.3.2', 'console_scripts', 'animdl')())
  File "c:\python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python39\lib\site-packages\animdl\core\cli\commands\continuation.py", line 57, in animdl_continue
    u, s, e, i, idm, au, ao, af, ac, am = sessions.generate_download_arguments(session)
ValueError: too many values to unpack (expected 10) ***
Whats wrong ? help pls !!!

**Comment by justfoolingaround** [comment]
Aight fixed. Just give `animdl` a reinstall.
