### ISSUE TITLE
[animepahe] Crash when there is no result

### ISSUE THREAD

**Issue by innocenzi** [justfoolingaround/animdl#27]
Hey,

Just to inform you that `animdl search "re zero s1" --provider=animepahe` fails:

```
Traceback (most recent call last):
  File "D:\Code\http\haishin\storage\animdl/animdl.py", line 29, in <module>
    __animdl_cli__()
  File "D:\Programmes\Python\3-8-0\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "D:\Programmes\Python\3-8-0\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "D:\Programmes\Python\3-8-0\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Programmes\Python\3-8-0\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Programmes\Python\3-8-0\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "D:\Code\http\haishin\storage\animdl\core\cli\helpers\fun.py", line 70, in internal
    return f(*args, **kwargs)
  File "D:\Code\http\haishin\storage\animdl\core\cli\commands\search.py", line 26, in animdl_search
    for i, search_data in enumerate(link.get(provider)(session, query)):
  File "D:\Code\http\haishin\storage\animdl\core\cli\helpers\searcher.py", line 64, in search_animepahe
    for results in content.get('data'):
TypeError: 'NoneType' object is not iterable
```

I think, but I'm not 100% sure, that it happens when there is no result.

It's not super important to me, just wanted to let you know. Hope you're not too bothered by my numerous issues, haha.

**Comment by justfoolingaround** [comment]
Aight, fixed. No worries lol, you can report as many as issues as you like!
