### ISSUE TITLE
TypeError: expected string or bytes-like object while streaming in animepahe

### ISSUE THREAD

**Issue by gamernoob24** [justfoolingaround/animdl#41]
idk why but i was streaming on animepahe and this comes up out of nowhere
the version is v1.3.6[git]

<pre>
Traceback (most recent call last):
  File "C:\Users\Jess\Downloads\Compressed\animdl\animdl.py", line 34, in <module>
    __animdl_cli__()
  File "C:\Users\Jess\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Jess\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Jess\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Jess\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Jess\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Jess\Downloads\Compressed\animdl\core\cli\helpers\fun.py", line 424, in internal
    return f(*args, **kwargs)
  File "C:\Users\Jess\Downloads\Compressed\animdl\core\cli\commands\stream.py", line 185, in animdl_stream
    selection = quality_prompt(stream_urls, provider) if len(
  File "C:\Users\Jess\Downloads\Compressed\animdl\core\cli\commands\stream.py", line 17, in quality_prompt
    'unknown' else '', stream_judiciary(anime.get('stream_url'))))
  File "C:\Users\Jess\Downloads\Compressed\animdl\core\cli\helpers\fun.py", line 409, in stream_judiciary
    match = URL_REGEX.search(url)
TypeError: expected string or bytes-like object
<pre>

**Comment by justfoolingaround** [comment]
What anime (and the episode) were you downloading?

**Comment by gamernoob24** [comment]
adachi to shimamura episode 2

**Comment by gamernoob24** [comment]
i tried it again to make sure and it now works just fine
and yes it did
idk why it happen but i think it's just the link

before:
<pre>
C:\Users\user\Downloads\Compressed\animdl>python animdl.py stream https://animepahe.com/anime/c6c8cc69-6c90-5758-e5fd-90205e2870a1
░█████╗░███╗░░██╗██╗███╗░░░███╗██████╗░██╗░░░░░
██╔══██╗████╗░██║██║████╗░████║██╔══██╗██║░░░░░
███████║██╔██╗██║██║██╔████╔██║██║░░██║██║░░░░░
██╔══██║██║╚████║██║██║╚██╔╝██║██║░░██║██║░░░░░
██║░░██║██║░╚███║██║██║░╚═╝░██║██████╔╝███████╗
╚═╝░░╚═╝╚═╝░░╚══╝╚═╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝v1.3.6[git]
A highly efficient anime downloader and streamer

[stream.py:117 - 2021-08-02 22:45:34,508 - animdl-animepahe-streamer-core: INFO] Now initiating your stream session
[stream.py:119 - 2021-08-02 22:45:34,510 - animdl-animepahe-streamer-core: INFO] Starting stream session @ [00/?]
[animdl-animepahe-url-selector] Found 3 stream(s)
[animdl-animepahe-url-selector] [#01] [Q.:360] '1fa5a1ab6b84c06f832e43a6caa0d2dc5f9fa80acd63d725a6f00f265b49530d' from files-eu-d1.nextstream.org
[animdl-animepahe-url-selector] [#02] [Q.:720] 'c8096632a5f3217ee78f3e8b69e560d95d34850f10bb3dbb3201f0891b836354' from files-na-d3.nextstream.org
[animdl-animepahe-url-selector] [#03] [Q.:1080] '426413725d95a1683a9e442e6465267f4223404f48fa09ee4342cf427a050c49' from files-na-d3.nextstream.org
[animdl-animepahe-streamer-core] Select by the index (defaults to 1):
[stream.py:189 - 2021-08-02 22:46:01,378 - animdl-animepahe-streamer-core: INFO] Active stream session @ [01/12]
[animdl-animepahe-url-selector] Found 3 stream(s)
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Compressed\animdl\animdl.py", line 34, in <module>
    __animdl_cli__()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\Downloads\Compressed\animdl\core\cli\helpers\fun.py", line 424, in internal
    return f(*args, **kwargs)
  File "C:\Users\user\Downloads\Compressed\animdl\core\cli\commands\stream.py", line 185, in animdl_stream
    selection = quality_prompt(stream_urls, provider) if len(
  File "C:\Users\user\Downloads\Compressed\animdl\core\cli\commands\stream.py", line 17, in quality_prompt
    'unknown' else '', stream_judiciary(anime.get('stream_url'))))
  File "C:\Users\user\Downloads\Compressed\animdl\core\cli\helpers\fun.py", line 409, in stream_judiciary
    match = URL_REGEX.search(url)
TypeError: expected string or bytes-like object
</pre>
after:
<pre>
C:\Users\Jess\Downloads\Compressed\animdl>python animdl.py search adachi
░█████╗░███╗░░██╗██╗███╗░░░███╗██████╗░██╗░░░░░
██╔══██╗████╗░██║██║████╗░████║██╔══██╗██║░░░░░
███████║██╔██╗██║██║██╔████╔██║██║░░██║██║░░░░░
██╔══██║██║╚████║██║██║╚██╔╝██║██║░░██║██║░░░░░
██║░░██║██║░╚███║██║██║░╚═╝░██║██████╔╝███████╗
╚═╝░░╚═╝╚═╝░░╚══╝╚═╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝v1.3.6[git]
A highly efficient anime downloader and streamer

[search.py:41 - 2021-08-03 06:11:29,905 - animdl-searcher: INFO] [#00] Adachi to Shimamura https://animepahe.com/anime/c6c8cc69-6c90-5758-e5fd-90205e2870a1

C:\Users\Jess\Downloads\Compressed\animdl>python animdl.py stream -s 2 https://animepahe.com/anime/c6c8cc69-6c90-5758-e5fd-90205e2870a1
░█████╗░███╗░░██╗██╗███╗░░░███╗██████╗░██╗░░░░░
██╔══██╗████╗░██║██║████╗░████║██╔══██╗██║░░░░░
███████║██╔██╗██║██║██╔████╔██║██║░░██║██║░░░░░
██╔══██║██║╚████║██║██║╚██╔╝██║██║░░██║██║░░░░░
██║░░██║██║░╚███║██║██║░╚═╝░██║██████╔╝███████╗
╚═╝░░╚═╝╚═╝░░╚══╝╚═╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝v1.3.6[git]
A highly efficient anime downloader and streamer

[stream.py:117 - 2021-08-03 06:11:43,713 - animdl-animepahe-streamer-core: INFO] Now initiating your stream session
[stream.py:119 - 2021-08-03 06:11:43,716 - animdl-animepahe-streamer-core: INFO] Starting stream session @ [02/?]
[animdl-animepahe-url-selector] Found 3 stream(s)
[animdl-animepahe-url-selector] [#01] [Q.:360] 'bd4b6ee9b2be9cf345c7185164a9f56a0310410658a7befae5f1d06035bcbdfd' from files-eu-d3.nextstream.org
[animdl-animepahe-url-selector] [#02] [Q.:720] 'a684182114762fdd6e93a10382eecf586c7f8309061afbaa6fc84256c186479d' from files-eu-d1.nextstream.org
[animdl-animepahe-url-selector] [#03] [Q.:1080] '2c2210e3c2e0c299894460f871c45f366d8ba38dce74b07a20e5ef52c00377df' from files-na-d2.nextstream.org
[animdl-animepahe-streamer-core] Select by the index (defaults to 1):
<pre>

**Comment by gamernoob24** [comment]
nvm still there

**Comment by justfoolingaround** [comment]
Should be fixed now! Thanks for reporting this issue!
