### ISSUE TITLE
Can't download but can stream from animepahe

### ISSUE THREAD

**Issue by shadow5013** [justfoolingaround/animdl#48]
For some reason, the download command is showing the following error today. Most probably cloudflare is doing something. But the stream command works fine. I wonder if the stream command is somehow bypassing cloudflare protection.
```python
░█████╗░███╗░░██╗██╗███╗░░░███╗██████╗░██╗░░░░░
██╔══██╗████╗░██║██║████╗░████║██╔══██╗██║░░░░░
███████║██╔██╗██║██║██╔████╔██║██║░░██║██║░░░░░
██╔══██║██║╚████║██║██║╚██╔╝██║██║░░██║██║░░░░░
██║░░██║██║░╚███║██║██║░╚═╝░██║██████╔╝███████╗
╚═╝░░╚═╝╚═╝░░╚══╝╚═╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝v1.3.9
A highly efficient anime downloader and streamer

[animdl-animepahe-searcher] [#01] Kure-nai https://animepahe.com/anime/6355cfc2-ef60-a62a-c598-0f22ca830c3b
[animdl-animepahe-searcher] [#02] Kure-nai OVA https://animepahe.com/anime/132b99e7-e85b-4585-c109-e7bc07959c25
[animdl-animepahe-searcher] [#03] Kurenai no Buta https://animepahe.com/anime/925005b3-ad9c-77fa-8b10-0f7e90ba0adc
[animdl-animepahe-searcher] [#04] Sakura Taisen: Le Nouveau Paris https://animepahe.com/anime/00dc519d-d044-8060-e89f-b95e3acfe909
Select by the index (defaults to 1): 
[download.py:109 - 2021-08-19 22:52:10,550 - animdl-animepahe-downloader-core: INFO] Initializing download session [00 -> ?]
[download.py:156 - 2021-08-19 22:52:11,638 - animdl-animepahe-downloader-core: INFO] Starting download session [00 -> 11]
[download.py:157 - 2021-08-19 22:52:11,638 - animdl-animepahe-downloader-core: INFO] Downloads will be done in the folder 'Kure-nai'
Traceback (most recent call last):
  File "/home/shadow/.local/bin/animdl", line 33, in <module>
    sys.exit(load_entry_point('animdl==1.3.9', 'console_scripts', 'animdl')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/shadow/.local/lib/python3.9/site-packages/animdl/core/cli/helpers/fun.py", line 424, in internal
    return f(*args, **kwargs)
  File "/home/shadow/.local/lib/python3.9/site-packages/animdl/core/cli/commands/download.py", line 233, in animdl_download
    url_download(
  File "/home/shadow/.local/lib/python3.9/site-packages/animdl/core/codebase/downloader/download.py", line 37, in single_threaded_download
    response_headers = session.head(
TypeError: head() got an unexpected keyword argument 'verify'
```

**Comment by justfoolingaround** [comment]
Oh woops. It isn't a Cloudflare related issue, this is an issue with `httpx` which didn't follow the same style of content download as `requests`. It should be fixed now!

**Comment by shadow5013** [comment]
Yup, problem solved.
