### ISSUE TITLE
Downloading from Animixplay throws an error after downloading few episodes

### ISSUE THREAD

**Issue by Kecerim24** [justfoolingaround/animdl#56]
```
Traceback (most recent call last):
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 180, in handle_request
    status_code, headers, byte_stream, extensions = self._pool.handle_request(
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\connection.py", line 148, in handle_request
    return self.connection.handle_request(
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http11.py", line 128, in handle_request
    ) = self._receive_response(timeout)
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http11.py", line 189, in _receive_response
    event = self._receive_event(timeout)
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http11.py", line 225, in _receive_event
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_backends\sync.py", line 61, in read
    return self.sock.recv(n)
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runner.py", line 35, in <module>
    __animdl_cli__()
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Mireček\Desktop\output\animdl-master\animdl\core\cli\helpers\fun.py", line 420, in internal
    return f(*args, **kwargs)
  File "C:\Users\Mireček\Desktop\output\animdl-master\animdl\core\cli\commands\download.py", line 160, in animdl_download
    stream_urls = stream_url_caller()
  File "C:\Users\Mireček\Desktop\output\animdl-master\animdl\core\codebase\providers\animixplay\stream_url.py", line 64, in <lambda>
    yield partial(lambda s, data_url: get_stream_url(s, data_url), session, data[str(value)]), value + 1
  File "C:\Users\Mireček\Desktop\output\animdl-master\animdl\core\codebase\providers\animixplay\stream_url.py", line 50, in get_stream_url
    url = get_embed(session, data_url)
  File "C:\Users\Mireček\Desktop\output\animdl-master\animdl\core\codebase\providers\animixplay\stream_url.py", line 37, in get_embed
    embed_page = session.get(
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1024, in get
    return self.request(
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 787, in request
    return self.send(
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 878, in send
    response = self._send_handling_auth(
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 908, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 947, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 983, in _send_single_request
    (status_code, headers, stream, extensions) = transport.handle_request(
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 180, in handle_request
    status_code, headers, byte_stream, extensions = self._pool.handle_request(
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Mireček\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out
PS C:\Users\Mireček\Desktop\output\animdl-master\animdl>
```

`python runner.py download https://animixplay.to/v1/serial-experiments-lain -s 9`

**Comment by justfoolingaround** [comment]
Problem seems to be associated with an unstable internet connection than `animdl` itself.

Did you re-run the command by changing the start index and saw if it persisted?

![unknown.png](https://user-images.githubusercontent.com/79979949/131463787-aa439918-b9e2-4bd5-9bac-e6d74f636a41.png)

I'm saying this due to the fact that I due to the fact that the `grab`, which goes by just grabbing urls seems to work flawlessly in my device.

_Also, don't use runner.py, it while it is even with animdl as a whole, it is kept just as a held as a basis for Nuitka. It is much more recommended to install it using pip and then accessing it from the console entry-point._
