### ISSUE TITLE
Please add alternate domains of Gogoanime

### ISSUE THREAD

**Issue by mohit83k** [justfoolingaround/animdl#78]
Gogoanime recently did some changes and it's redirecting to alternate domains. 

https://gogoanime.wiki
https://gogoanime.cm

`>animdl grab -f 1 https://gogoanime.wiki/kaifuku-jutsushi-no-yarinaoshi-uncensored-episode-1
░█████╗░███╗░░██╗██╗███╗░░░███╗██████╗░██╗░░░░░
██╔══██╗████╗░██║██║████╗░████║██╔══██╗██║░░░░░
███████║██╔██╗██║██║██╔████╔██║██║░░██║██║░░░░░
██╔══██║██║╚████║██║██║╚██╔╝██║██║░░██║██║░░░░░
██║░░██║██║░╚███║██║██║░╚═╝░██║██████╔╝███████╗
╚═╝░░╚═╝╚═╝░░╚══╝╚═╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝v1.3.7
A highly efficient anime downloader and streamer

[processors.py:12 - 2021-11-06 19:02:40,051 - animdl-grabber-core: CRITICAL] Failed to find anything of that query on 'animepahe'. Try searching on other providers.`

**Comment by ArjixWasTaken** [comment]
Just make a file named `animdl_config.yml` and place it somewhere, then add it as an environment variable with the name `ANIMDL_CONFIG`

After that open that file and write in:
```yaml
---
site_urls:
  gogoanime: https://gogoanime.cm/
```

that should do it

**Comment by mohit83k** [comment]
![image](https://user-images.githubusercontent.com/17878921/140651480-d14c5a9b-52ba-41c4-8270-05311dac1fe6.png)
![image](https://user-images.githubusercontent.com/17878921/140651510-a73e584d-a5f6-4b3e-be89-099641c1c9b5.png)

`C:\Users\mohit\Downloads\animdl-config>animdl grab -f 1 https://gogoanime.cm/boruto-naruto-next-generations-episode-223
Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\animdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('animdl==1.3.7', 'console_scripts', 'animdl')())
  File "C:\Program Files\Python39\Scripts\animdl-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Program Files\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Program Files\Python39\lib\site-packages\animdl\__main__.py", line 8, in <module>
    from .core.cli.commands import download, stream, grab, schedule, test, search
  File "C:\Program Files\Python39\lib\site-packages\animdl\core\cli\commands\download.py", line 7, in <module>
    from ...config import AUTO_RETRY, QUALITY, USE_FFMPEG
  File "C:\Program Files\Python39\lib\site-packages\animdl\core\config\__init__.py", line 65, in <module>
    CONFIG = merge_dicts(DEFAULT_CONFIG, yaml.load(conf))
TypeError: load() missing 1 required positional argument: 'Loader'`

It tried to follow the fix but it gave me this error.

**Comment by mohit83k** [comment]
I also tried to remove `---` from the yml file but still got same error.

**Comment by ArjixWasTaken** [comment]
Lmao, @Justaus3r fix

**Comment by justfoolingaround** [comment]
Sorry for the late response!

I have applied all the fixes necessary and now GogoAnime should work!

`pyyaml` recently removed `FullLoader` as their default loader and made it so that the package would need to specify a loader.

I have updated the GogoAnime urls and now if any url change occurs, you can simply change the urls from the config until it gets upstreamed in animdl.
