### ISSUE TITLE
Trying to stream anything results in errors

### ISSUE THREAD

**Issue by sripadks** [justfoolingaround/animdl#85]
After the latest update, when I try to stream something, it errors out and exits (with python 3.10). Not sure if it has got anything to do with python version but here is the error it produces. Will be glad to provide any additional logging if required.

```
PS C:\Users\sripad> animdl stream "Saihate no Paladin" -r 1-
                                                         justfoolingaround/animdl - v1.4.0
                                                  A highly efficient anime downloader and streamer
[processors.py:15 - 2021-12-04 17:02:15,964 - streamer: I] 01: Saihate no Paladin https://animepahe.com/anime/3f51da9c-8a2e-bf7d-1e0f-b679aac04719
[stream.py:96 - 2021-12-04 17:02:15,965 - animepahe/streamer: I] Now initiating your stream session
Traceback (most recent call last):
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\Scripts\animdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('animdl==1.4.0', 'console_scripts', 'animdl')())
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\helpers\fun.py", line 119, in internal
    return f(*args, **kwargs)
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\commands\stream.py", line 110, in animdl_stream
    stream_urls = list(helpers.ensure_extraction(session, stream_urls_caller))
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\cli\helpers\__init__.py", line 35, in ensure_extraction
    for stream in stream_uri_caller():
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\codebase\providers\animepahe\__init__.py", line 60, in <lambda>
    yield partial(lambda session, release_id, content: ([*get_stream_url(session, release_id, content.get('session'))]), session, release_id, content), content.get('episode', 0)
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\codebase\providers\animepahe\__init__.py", line 53, in get_stream_url
    yield {'quality': quality, 'headers': {'referer': data.get('kwik')}, 'stream_url': get_stream_url_from_kwik(session, data.get('kwik_adfly'))}
  File "C:\Users\sripad\AppData\Local\Programs\Python\Python310\lib\site-packages\animdl\core\codebase\providers\animepahe\inner\__init__.py", line 57, in get_stream_url_from_kwik
    f_content.text).group(
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by justfoolingaround** [comment]
OOPS!

I kinda swapped AnimePahe's internal algorithm for the Cloudflare handling a while ago.

I should work now with a reinstall (because the version numbers for this push haven't be updated.)

```
pip uninstall animdl && pip install git+https://github.com/justfoolingaround/animdl/
```

**Comment by sripadks** [comment]
Can confirm it works now. Thanks 👍
