### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by karimelgazar** [justfoolingaround/animdl#90]
after I install the `animdl` then I try to use it I get this error 

`RecursionError: maximum recursion depth exceeded while calling a Python object`

here's the whole traceback

```
Traceback (most recent call last):
  File "/usr/local/bin/animdl", line 5, in <module>
    from animdl.__main__ import __animdl_cli__
  File "/usr/local/lib/python3.7/dist-packages/animdl/__main__.py", line 8, in <module>
    from .core.cli.commands import download, stream, grab, schedule, test, search
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/commands/download.py", line 8, in <module>
    from .. import exit_codes, helpers, http_client
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/__init__.py", line 9, in <module>
    from .fun import (bannerify, choice, create_random_titles, stream_judiciary,
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/fun.py", line 47, in <module>
    """.format(__core__))
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/fun.py", line 42, in terminal_center
    return '\n'.join(genexp())
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/fun.py", line 40, in genexp
    for piece in line_chop(line, columns):
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/fun.py", line 34, in line_chop
    yield from line_chop(string[sep_index + len(sep):], max_length, separators=separators)
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/fun.py", line 34, in line_chop
    yield from line_chop(string[sep_index + len(sep):], max_length, separators=separators)
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/fun.py", line 34, in line_chop
    yield from line_chop(string[sep_index + len(sep):], max_length, separators=separators)
  [Previous line repeated 956 more times]
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/fun.py", line 28, in line_chop
    sep, sep_index = max(((_, string[:max_length].rfind(_)) for _ in separators), key=lambda x: x[1])
  File "/usr/local/lib/python3.7/dist-packages/animdl/core/cli/helpers/fun.py", line 28, in <genexpr>
    sep, sep_index = max(((_, string[:max_length].rfind(_)) for _ in separators), key=lambda x: x[1])
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by justfoolingaround** [comment]
Uhhh, this is actually an weird issue.

Can you please run 
```py
py -c "print(__import__('os').get_terminal_size())
```
In the terminal where this exact error occurs.

**Comment by karimelgazar** [comment]
sure 
I am testing `animedl` on google colab
hare this the output 
```python
os.terminal_size(columns=0, lines=0)
```

**Comment by justfoolingaround** [comment]
Aight, should be fixed after this.

Never thought I'd see that terminal size lmao.

**Comment by karimelgazar** [comment]
Awesome Work @justfoolingaround :tada:
