### ISSUE TITLE
Error when decoding json

### ISSUE THREAD

**Issue by gavieira** [justfoolingaround/animdl#99]
Up until yesterday, the script was working normally. Today, even after installing the newest version, I'm getting the following error (using animepahe) both on manjaro and arch:

$> animdl download -r 1- "Mob Psycho 100"

                       justfoolingaround/animdl - v1.4.45                       
                A highly efficient anime downloader and streamer                
Traceback (most recent call last):
  File "/home/agatinha/.local/bin/animdl", line 33, in <module>
    sys.exit(load_entry_point('animdl==1.4.45', 'console_scripts', 'animdl')())
  File "/home/agatinha/.local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/agatinha/.local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/agatinha/.local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/agatinha/.local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/agatinha/.local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/agatinha/.local/lib/python3.10/site-packages/animdl/core/cli/helpers/fun.py", line 153, in internal
    return f(*args, **kwargs)
  File "/home/agatinha/.local/lib/python3.10/site-packages/animdl/core/cli/commands/download.py", line 71, in animdl_download
    anime, provider = helpers.process_query(
  File "/home/agatinha/.local/lib/python3.10/site-packages/animdl/core/cli/helpers/processors.py", line 67, in process_query
    return prompt_user(logger, genexp, searcher.provider)
  File "/home/agatinha/.local/lib/python3.10/site-packages/animdl/core/cli/helpers/processors.py", line 9, in prompt_user
    expansion = [*anime_list_genexp]
  File "/home/agatinha/.local/lib/python3.10/site-packages/animdl/core/cli/helpers/searcher.py", line 83, in search_animepahe
    content = animepahe_results.json()
  File "/home/agatinha/.local/lib/python3.10/site-packages/httpx/_models.py", line 1433, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by justfoolingaround** [comment]
Hey there! looking at what happened, the searcher probably died because the site added Cloudflare or was inactive at that specific time. 

All is working while I'm testing animdl.

**Comment by gavieira** [comment]
The problem must be on my end then. Still having the same problem with animepahe here, but gogoanime and other sites are working flawlessly, so I'll just use them for now.

Thanks for both the feedback and this amazing tool! :)
